# Generated by Django 4.2.6 on 2023-10-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
